blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Stratose/sprinkler-business-app/tree/main/docs
    about: View project documentation and requirements
  - name: 🚀 Live Demo
    url: http://localhost:5173
    about: Access the development server (when running locally)
