name: 🔧 DevOps
description: Infrastructure, deployment, and tooling tasks
title: "[DEVOPS] "
labels: ["🔧 devops", "📋 needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## DevOps Task
        Use this template for infrastructure, deployment, CI/CD, and tooling tasks.

  - type: input
    id: devops-title
    attributes:
      label: Task Summary
      description: A brief description of the DevOps task
      placeholder: "Set up automated deployment to Vercel"
    validations:
      required: true

  - type: dropdown
    id: devops-category
    attributes:
      label: Category
      description: What type of DevOps task is this?
      options:
        - CI/CD Pipeline
        - Deployment
        - Infrastructure
        - Monitoring
        - Security
        - Performance
        - Tooling
        - Environment Setup
        - Database Management
        - Other
    validations:
      required: true

  - type: textarea
    id: devops-description
    attributes:
      label: Description
      description: Detailed description of what needs to be done
      placeholder: "Configure GitHub Actions workflow to automatically deploy to Vercel on main branch pushes"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment(s) are affected?
      options:
        - Development
        - Staging
        - Production
        - All Environments
        - CI/CD Pipeline
        - Local Development
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this task?
      options:
        - Low - Nice to have improvement
        - Medium - Important for efficiency
        - High - Required for deployment
        - Critical - Blocking development or production
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what "done" looks like for this task
      placeholder: |
        - [ ] GitHub Actions workflow configured
        - [ ] Automatic deployment on main branch push
        - [ ] Environment variables properly set
        - [ ] Deployment status notifications working
        - [ ] Rollback procedure documented
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Any specific technical requirements or constraints
      placeholder: "Must use GitHub Actions, integrate with Vercel, handle environment variables securely"

  - type: textarea
    id: security-considerations
    attributes:
      label: Security Considerations
      description: Any security implications or requirements
      placeholder: "Secure handling of API keys, access controls, etc."

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Reference related issues or dependencies
      placeholder: "#123, #456"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have considered security implications
          required: true
        - label: I have identified any dependencies
          required: true
        - label: This task aligns with our deployment strategy
          required: true
